config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get "signin" => "devise/sessions#new"
    delete "signout" => "devise/sessions#destroy"
    get "signup" => "devise/registration#new"
  end
  root 'pages#home'
  get 'about' => 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My website</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-inverse"
      <div class="container">
        <ul class=class: "nav navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "about", about_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item pull-md-right">
              <%= link_to "Log out", signout_path, method: :delete, class: "nav-link btn btn-primary" %>
            </li>
          <% else %>
            <li class="nav-item pull-md-right">
              <%= link_to "Sign up", signup_path, class: "nav-link btn btn-primary" %>
            </li>
            <li class="nav-item pull-md-right">
              <%= link_to "Sign in", signin_path, class: "nav-link btn btn-primary" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <!-- Flash Messager -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-into #{name}") %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>Learn ruby on rails</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    <h1>Welcome back!!</h1>
<% else %>

    <h1>Welcome to my website!</h1>
    <p>đang làm</p>
    
<% end %>